In [6]:
import numpy as np

In [7]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])

In [8]:
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [9]:
two_da = np.array([[1,5],[5,5],[3,6]])

In [10]:
two_da

array([[1, 5],
       [5, 5],
       [3, 6]])

In [11]:
print(two_da)

[[1 5]
 [5 5]
 [3 6]]


In [12]:
sq = np.arange(5,55)

In [13]:
random_array = np.random.randint(low=8, high=120, size=(6))
random_array

array([ 45,  93, 104, 116,  43,  58])

In [14]:
random_float = np.random.random([5])
random_float

array([0.92053583, 0.05351055, 0.31284468, 0.12677473, 0.17741289])

In [15]:
random_float2 = random_float + 2.0
random_float2

array([2.92053583, 2.05351055, 2.31284468, 2.12677473, 2.17741289])

In [16]:
random_array2 = random_array * 3

In [17]:
random_array2

array([135, 279, 312, 348, 129, 174])

In [18]:
feature = np.arange(6,21)

In [19]:
feature

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
label = (feature * 3) + 4

In [21]:
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [22]:
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [23]:
len(label)

15

In [24]:
noise = np.random.random([15])

In [25]:
noise

array([0.79860224, 0.06468669, 0.30898818, 0.98005685, 0.46843438,
       0.8796474 , 0.72143785, 0.40488434, 0.33686376, 0.60359845,
       0.40927067, 0.53120891, 0.41710437, 0.95660148, 0.09342119])

In [26]:
noise = (noise*3)+4

In [27]:
noise


array([6.39580673, 4.19406006, 4.92696453, 6.94017054, 5.40530313,
       6.63894219, 6.16431356, 5.21465303, 5.01059127, 5.81079536,
       5.22781201, 5.59362673, 5.2513131 , 6.86980443, 4.28026358])

In [28]:
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [29]:
noise = (np.random.random([15])*4) - 2

In [30]:
noise


array([-1.50135297,  0.54656235,  1.82629352,  0.41897712,  0.40703296,
       -1.70135165, -0.60462619,  0.51836331, -0.24358231, -0.8263979 ,
       -0.43651363, -0.44538679,  1.05879836,  1.57024202,  1.25609904])

In [31]:
noise

array([-1.50135297,  0.54656235,  1.82629352,  0.41897712,  0.40703296,
       -1.70135165, -0.60462619,  0.51836331, -0.24358231, -0.8263979 ,
       -0.43651363, -0.44538679,  1.05879836,  1.57024202,  1.25609904])

In [32]:
noise = np.random.random([20]) * 4

In [33]:
noise

array([3.18189082, 2.11986979, 3.82775273, 0.79498254, 2.239817  ,
       0.45489677, 1.41273495, 0.90666661, 2.42641058, 0.75490611,
       3.45074378, 0.15422856, 3.6778258 , 0.22023919, 0.5608923 ,
       3.77849452, 1.05892329, 1.55299702, 0.3490216 , 0.8621087 ])

In [34]:
noise = (np.random.random([20]) * 4) - 2

In [35]:
noise

array([ 0.18345654,  0.17944116,  1.71051609, -0.20200984, -1.33572291,
       -0.86493793, -0.92940372,  0.99778504, -1.22144593,  0.17631209,
       -1.63499581, -1.72406067, -1.31476017, -0.78362904, -0.4800281 ,
       -0.21720965,  1.83530333, -1.14523102, -0.86979366, -0.89156863])

In [36]:
print(noise)

[ 0.18345654  0.17944116  1.71051609 -0.20200984 -1.33572291 -0.86493793
 -0.92940372  0.99778504 -1.22144593  0.17631209 -1.63499581 -1.72406067
 -1.31476017 -0.78362904 -0.4800281  -0.21720965  1.83530333 -1.14523102
 -0.86979366 -0.89156863]


In [37]:
noise

array([ 0.18345654,  0.17944116,  1.71051609, -0.20200984, -1.33572291,
       -0.86493793, -0.92940372,  0.99778504, -1.22144593,  0.17631209,
       -1.63499581, -1.72406067, -1.31476017, -0.78362904, -0.4800281 ,
       -0.21720965,  1.83530333, -1.14523102, -0.86979366, -0.89156863])

In [38]:
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [39]:
np

<module 'numpy' from 'C:\\Users\\srija\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [41]:
labe = np.array([5,5])

In [42]:
labe

array([5, 5])