In [1]:
import numpy as np

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])

In [3]:
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [4]:
two_da = np.array([[1,5],[5,5],[3,6]])

In [5]:
two_da

array([[1, 5],
       [5, 5],
       [3, 6]])

In [6]:
print(two_da)

[[1 5]
 [5 5]
 [3 6]]


In [7]:
sq = np.arange(5,55)

In [8]:
random_array = np.random.randint(low=8, high=120, size=(6))
random_array

array([ 97, 109,  21,  30,  81,  76])

In [9]:
random_float = np.random.random([5])
random_float

array([0.27558622, 0.70101904, 0.2496991 , 0.74521213, 0.7891361 ])

In [10]:
random_float2 = random_float + 2.0
random_float2

array([2.27558622, 2.70101904, 2.2496991 , 2.74521213, 2.7891361 ])

In [11]:
random_array2 = random_array * 3

In [12]:
random_array2

array([291, 327,  63,  90, 243, 228])

In [13]:
feature = np.arange(6,21)

In [14]:
feature

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
label = (feature * 3) + 4

In [16]:
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [17]:
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [18]:
len(label)

15

In [19]:
noise = np.random.random([15])

In [20]:
noise

array([0.33463375, 0.72431246, 0.74617504, 0.24011298, 0.92890196,
       0.61690194, 0.6137948 , 0.43867693, 0.37732475, 0.50620241,
       0.07778106, 0.56356027, 0.62140068, 0.64358501, 0.21165377])

In [21]:
noise = (noise*3)+4

In [22]:
noise


array([5.00390124, 6.17293738, 6.23852511, 4.72033895, 6.78670588,
       5.85070583, 5.8413844 , 5.31603078, 5.13197424, 5.51860723,
       4.23334317, 5.69068082, 5.86420204, 5.93075502, 4.6349613 ])

In [23]:
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [24]:
noise = (np.random.random([15])*4) - 2

In [25]:
noise


array([ 1.6411277 ,  1.06314737, -1.07478573, -0.45027588, -0.92001795,
        0.08270339, -0.31867534,  1.12033175, -0.74722294, -1.44325309,
       -1.3972441 , -0.75692485, -1.7702011 ,  1.51509851, -0.48351443])

In [26]:
noise

array([ 1.6411277 ,  1.06314737, -1.07478573, -0.45027588, -0.92001795,
        0.08270339, -0.31867534,  1.12033175, -0.74722294, -1.44325309,
       -1.3972441 , -0.75692485, -1.7702011 ,  1.51509851, -0.48351443])

In [27]:
noise = np.random.random([20]) * 4

In [28]:
noise

array([3.48269588, 1.07864129, 2.68374941, 1.86660723, 1.21461051,
       3.79304098, 3.02865691, 2.26855366, 3.8033753 , 2.87393299,
       1.72610904, 0.45053881, 2.84972963, 0.2729643 , 0.95346151,
       2.88535254, 0.96313999, 0.74893869, 2.37906281, 0.16701876])

In [29]:
noise = (np.random.random([20]) * 4) - 2

In [30]:
noise

array([ 1.85370403, -0.20567196,  0.40641877, -0.8933026 , -0.6002115 ,
       -0.66471644, -1.62072868, -1.93393816, -1.71637304,  1.13268035,
        1.33770799,  0.25926996,  0.80070492, -1.77644367,  0.6167926 ,
       -0.85704574, -1.24150251, -1.73762062, -1.70775779,  0.40449067])

In [31]:
print(noise)

[ 1.85370403 -0.20567196  0.40641877 -0.8933026  -0.6002115  -0.66471644
 -1.62072868 -1.93393816 -1.71637304  1.13268035  1.33770799  0.25926996
  0.80070492 -1.77644367  0.6167926  -0.85704574 -1.24150251 -1.73762062
 -1.70775779  0.40449067]


In [32]:
noise

array([ 1.85370403, -0.20567196,  0.40641877, -0.8933026 , -0.6002115 ,
       -0.66471644, -1.62072868, -1.93393816, -1.71637304,  1.13268035,
        1.33770799,  0.25926996,  0.80070492, -1.77644367,  0.6167926 ,
       -0.85704574, -1.24150251, -1.73762062, -1.70775779,  0.40449067])

In [33]:
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [34]:
np

<module 'numpy' from 'F:\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [35]:
labe = np.array([5,5])

In [36]:
labe

array([5, 5])