In [1]:
import numpy as np
import pandas as pd

In [2]:
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

In [3]:
my_column_names = ['temperature', 'activity']

In [4]:
my_data

array([[ 0,  3],
       [10,  7],
       [20,  9],
       [30, 14],
       [40, 15]])

In [5]:
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

In [6]:
my_dataframe

temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15

In [7]:
my_dataframe['adjusted'] = my_dataframe['activity'] + 2

In [8]:
my_dataframe

temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17

In [9]:
my_dataframe.head(2)

temperature  activity  adjusted
0            0         3         5
1           10         7         9

In [10]:
my_dataframe.iloc[[2]]

temperature  activity  adjusted
2           20         9        11

In [11]:
my_dataframe.iloc[[2, 4, 1]]

temperature  activity  adjusted
2           20         9        11
4           40        15        17
1           10         7         9

In [12]:
my_dataframe[1:4]

temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16

In [13]:
my_dataframe['temperature']

0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32

In [14]:
row1 = np.random.randint(0,101,4)

In [15]:
row1

array([14, 87, 78, 30])

In [16]:
row2 = np.random.randint(0,101,4)
row3 = np.random.randint(0,101,4)

In [17]:
data = np.array([row1,row2,row3])

In [18]:
data

array([[14, 87, 78, 30],
       [31, 46, 64, 47],
       [33, 44, 33, 37]])

In [19]:
column_titles = ['Eleanor', 'Chidi', 'Thahani', 'Jason']

In [20]:
dataframe = pd.DataFrame(data, columns=column_titles)

In [21]:
dataframe

Eleanor  Chidi  Thahani  Jason
0       14     87       78     30
1       31     46       64     47
2       33     44       33     37

In [22]:
dataframe['Eleanor'].iloc[[1]]

1    31
Name: Eleanor, dtype: int32

In [23]:
dataframe['Janet'] = dataframe['Thahani'] + dataframe['Jason']

In [24]:
dataframe

Eleanor  Chidi  Thahani  Jason  Janet
0       14     87       78     30    108
1       31     46       64     47    111
2       33     44       33     37     70

In [25]:
op = dataframe

In [26]:
op

Eleanor  Chidi  Thahani  Jason  Janet
0       14     87       78     30    108
1       31     46       64     47    111
2       33     44       33     37     70

In [27]:
dataframe

Eleanor  Chidi  Thahani  Jason  Janet
0       14     87       78     30    108
1       31     46       64     47    111
2       33     44       33     37     70

In [28]:
op['new'] = 5

In [29]:
op

Eleanor  Chidi  Thahani  Jason  Janet  new
0       14     87       78     30    108    5
1       31     46       64     47    111    5
2       33     44       33     37     70    5

In [30]:
dataframe

Eleanor  Chidi  Thahani  Jason  Janet  new
0       14     87       78     30    108    5
1       31     46       64     47    111    5
2       33     44       33     37     70    5

In [31]:
dataframe

Eleanor  Chidi  Thahani  Jason  Janet  new
0       14     87       78     30    108    5
1       31     46       64     47    111    5
2       33     44       33     37     70    5